export const MURPHY_COUNTER_PLUS_ONE = 'MURPHY_COUNTER_PLUS_ONE';
export const MURPHY_COUNTER_MINUS_ONE = 'MURPHY_COUNTER_MINUS_ONE';
export const MURPHY_COUNTER_RESET = 'MURPHY_COUNTER_RESET';
export const MURPHY_FETCH_INTELIPOST_LIST_BEGIN = 'MURPHY_FETCH_INTELIPOST_LIST_BEGIN';
export const MURPHY_FETCH_INTELIPOST_LIST_SUCCESS = 'MURPHY_FETCH_INTELIPOST_LIST_SUCCESS';
export const MURPHY_FETCH_INTELIPOST_LIST_FAILURE = 'MURPHY_FETCH_INTELIPOST_LIST_FAILURE';
export const MURPHY_FETCH_INTELIPOST_LIST_DISMISS_ERROR = 'MURPHY_FETCH_INTELIPOST_LIST_DISMISS_ERROR';
